apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pos-txn-monitor-kapp-cluster-installer-role
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pos-txn-monitor-kapp-cluster-installer-role-binding
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pos-txn-monitor-kapp-cluster-installer-role
subjects:
- kind: ServiceAccount
  name: pos-txn-monitor-installer
  namespace: pos-txn-monitor-kapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pos-txn-monitor-installer
  namespace: pos-txn-monitor-kapp
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
