apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery-relocate
spec:
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
  - name: image-relocate
    sources:
    - name: source-image
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: image-relocate
    params:
    - name: local_repo
      value: registry.mk.aws.grogscave.net/app
  - name: deployer
    deployment:
      resource: image-relocate
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy-edge
  selector:
    app.tanzu.vmware.com/deliverable-type: edge-relocate