---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: image-relocate
spec:
  revisionPath: .status.outputs.relocatedBundle
  urlPath: .status.outputs.relocatedBundle
  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: image-relocate
    spec:
      runTemplateRef:
        name: image-relocate
      inputs:
        repository: $(source.url)$
        revision: $(source.revision)$
        local_repo: $(params.local_repo)$