---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: image-relocate
spec:
  revisionPath: .status.taskResults[?(@.name == 'relocatedBundle')].value
  urlPath: .status.taskResults[?(@.name == 'relocatedBundle')].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: imgpkg-relocate
    spec:
      taskSpec:
        results:
        - name: relocatedBundle
        steps:
          - name: relocate
            image: harbor.eqix.vmwedge.com/tekton-task-images/imgpkg-kbld:latest
            script: |
              imgpkg copy -b $(sources.source-image.revision)$ --to-repo $(params.local_repo)$  --registry-username $(params.remote_username)$ --registry-password $(params.remote_password)$ --lock-output bundle.yaml --registry-verify-certs=false
              grep image bundle.yaml | awk '{print $2}' > $(results.relocatedBundle.path)