apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-test-scan-to-url-edge
spec:
  params:
  - name: maven_repository_url
    value: https://repo.maven.apache.org/maven2
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: source-tester
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
  - name: source-scanner
    params:
    - default: scan-policy
      name: scanning_source_policy
    - default: blob-source-scan-template
      name: scanning_source_template
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterSourceTemplate
      name: source-scanner-template
  - name: image-provider
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: apps
        server: harbor.eqix.vmwedge.com
    - default: default
      name: clusterBuilder
    - default: ./Dockerfile
      name: dockerfile
    - default: ./
      name: docker_build_context
    - default: []
      name: docker_build_extra_args
    sources:
    - name: source
      resource: source-scanner
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: kpack-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: DoesNotExist
      - name: kaniko-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: Exists
  - name: image-scanner
    images:
    - name: image
      resource: image-provider
    params:
    - default: scan-policy
      name: scanning_image_policy
    - default: private-image-scan-template
      name: scanning_image_template
    templateRef:
      kind: ClusterImageTemplate
      name: image-scanner-template
  - name: app-config
    images:
    - name: image
      resource: image-scanner
    templateRef:
      kind: ClusterConfigTemplate
      options:
      - name: config-template-edge
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: edge
      - name: server-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: server
      - name: worker-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: worker
  - name: service-bindings
    configs:
    - name: app_def
      resource: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
  - name: api-descriptors
    configs:
    - name: app_def
      resource: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
  - name: config-writer
    configs:
    - name: config
      resource: api-descriptors
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: apps
        server: harbor.eqix.vmwedge.com
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template-lock
  - name: deliverable-config-writer
    params:
    - name: registry
      value:
        ca_cert_data: ""
        repository: apps
        server: harbor.eqix.vmwedge.com
    templateRef:
      kind: ClusterConfigTemplate
      name: deliverable-config-writer
  - name: deliverable-git-writer
    configs:
    - name: config
      resource: deliverable-config-writer
    params:
    - name: gitops_server_address
      value: ssh://git@github.com
    - name: gitops_repository_owner
      value: mwright-pivotal
    - name: gitops_repository_name
      value: POSTxnMonitor-ops
    - name: gitops_branch
      value: dev
    - name: gitops_user_name
      value: mwright-pivotal
    - name: gitops_user_email
      value: wrightmi@vmware.com
    - name: gitops_commit_message
      value: Update from supply chain
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  - name: deliverable
    params:
    - name: registry
      value:
        ca_cert_data: ""
        repository: apps
        server: harbor.eqix.vmwedge.com
    templateRef:
      kind: ClusterTemplate
      name: simple-apply
  selector:
    apps.tanzu.vmware.com/has-tests: "true"
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - edge