apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-sensors-delivery
spec:
  fetch:
  - git:
      url: https://github.com/cdelashmutt-pivotal/edge-deliverable
      ref: origin/main
      subPath: config/edge/spring-sensors
  template:
  - ytt: {}
  deploy:
  - kapp: {}
  serviceAccountName: default
  syncPeriod: 1m0s